[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-w = "straight"
u = "toothed"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-serifless"
eight = "crossing"
nine = "straight-bar"
asterisk = "turn-hex-low"
at = "fourfold-tall"
dollar = "through"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.iosevka-custom.ligations]
  inherits = "swift"
